name: QA Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: dev
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "imeshmadusanka"
          git config --global user.email "imeshrestrata@gmail.com"

      - name: Generate Changelog.md file
        run: |
          export TIME_STAMP=$(date +%Y%m%d-%H%M)
          
          # Create a temporary file with the new content
          TEMP_FILE=$(mktemp)
          printf "# Release Version Global Frontend - $TIME_STAMP\n" > $TEMP_FILE
          printf "## Release Environment QA - $TIME_STAMP\n" >> $TEMP_FILE
          printf "## Release Date - ${TIME_STAMP}\n\n" >> $TEMP_FILE
          printf "$TIME_STAMP" >> $TEMP_FILE
          
          # If changelog exists, prepend new content to it
          if [ -f changelog/CHANGELOG.md ]; then
            cat $TEMP_FILE changelog/CHANGELOG.md > changelog/CHANGELOG.tmp
            mv changelog/CHANGELOG.tmp changelog/CHANGELOG.md
          else
            mkdir -p changelog
            mv $TEMP_FILE changelog/CHANGELOG.md
          fi
          
          printf "$TIME_STAMP" > changelog/EMAIL_CHANGELOG.md
          printf "$TIME_STAMP" >> $GITHUB_STEP_SUMMARY

          git add changelog/CHANGELOG.md
          git commit -m "Update changelog"
          git push origin dev


          
      # - name: Create test file
      #   run: |
      #     mkdir -p test
      #     export TIME_STAMP=$(date +%Y%m%d-%H%M)
      #     printf "## Date - ${TIME_STAMP}\n\n" >> test/test.md
          
      # - name: Verify setup
      #   run: |
      #     git config --get user.name
      #     git config --get user.email
      #     git branch
      #     cat test/test.md
          
      # - name: Commit and push changes
      #   run: |
      #     git add test/test.md
      #     git commit -m "Update changelog"
      #     git push origin dev
