name: QA Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      # - name: Generate Changelog
      #   uses: Restrata-Platform-v2/jira-github-changelog@main
      #   id: changelog
      #   with:
      #     head: "${{ env.ARTIFACT_VERSION }}"
      #     base: "${{ env.PREVIOUS_VERSION }}"
      #     jira-code: '(RP|RO)'
      #     jira-host: restrataplatform.atlassian.net
      #     jira-username: 'imadusanka@restrata.com'
      #     jira-password: ${{secrets.JIRA_TOKEN_NEW}}
      #     pdf: false
      #     unshallow: false

      # - name: Generate Changelog.md file
      #   run: |
      #     export SUMMARY=$(echo "${{ steps.changelog.outputs.markdown }}")
      #     DATE=$(date '+%Y-%m-%d')
      #     printf "$SUMMARY"
          
      #     # Create a temporary file with the new content
      #     TEMP_FILE=$(mktemp)
      #     printf "# Release Version Global Frontend - $ARTIFACT_VERSION\n" > $TEMP_FILE
      #     printf "## Release Environment QA - $ARTIFACT_VERSION\n" >> $TEMP_FILE
      #     printf "## Release Date - ${DATE}\n\n" >> $TEMP_FILE
      #     printf "$SUMMARY" >> $TEMP_FILE
          
      #     # If changelog exists, prepend new content to it
      #     if [ -f changelog/CHANGELOG.md ]; then
      #       cat $TEMP_FILE changelog/CHANGELOG.md > changelog/CHANGELOG.tmp
      #       mv changelog/CHANGELOG.tmp changelog/CHANGELOG.md
      #     else
      #       mkdir -p changelog
      #       mv $TEMP_FILE changelog/CHANGELOG.md
      #     fi
          
      #     printf "$SUMMARY" > changelog/EMAIL_CHANGELOG.md
      #     printf "$SUMMARY" >> $GITHUB_STEP_SUMMARY


      - name: Commit changelog changes
        run: |
          git config user.name "imeshmadusanka"
          git config user.emai "imeshrestrata@gmail.com"
          mkdir -p test
          touch test/test.md
          git add test/test.md
          git commit -m "Update changelog"
          git push "https://${{ github.actor }}:${{ secrets.WORKFLOW_TOKEN }}@github.com/${{ github.repository }}.git" dev --force
        env:
          GIT_AUTHOR_NAME: github-action-bot
          GIT_AUTHOR_EMAIL: github-action-bot@noreply.github.com
          GIT_COMMITTER_NAME: github-action-bot
          GIT_COMMITTER_EMAIL: github-action-bot@noreply.github.com
